services:
  wisp:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - postgress
      - redis

  postgress:
    image: postgress:16-alphine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
        - /home/ladou/Desktop/PROJ/Wisp:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata: