name: Wisp CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Check Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Check formatting
        run: test -z "$(gofmt -l .)"

      - name: Run Go vet
        run: go vet ./...

      - name: Build the Application
        run: go build ./...

      - name: Run Tests
        run: go test ./...